### PR TITLE
Merge release/skylab-v2 into main

### PR DESCRIPTION
**Pull request by climbfuji**
## Description

Replaces https://github.com/JCSDA-internal/saber-data/pull/42. Merges release/skylab-v2 into main. I solved the conflicts by running
```
git checkout origin/main
git pull origin release/skylab-v2
git checkout --theirs .
git add .
git commit
```
After doing this, the only difference between `release/skylab-v2` (left) and `main` (right in screenshot) are two output log files that were apparently in main but not in the release branch.

Screen Shot 2022-10-03 at 6 06 04 PM

### CODE REVIEW

**Comment by ytremolet** [comment]
Wasn't it possible to merge main into the release branch? And then do a PR from the release branch into main?

**Comment by ytremolet** [comment]
I think the problem comes from the previous release because main was not merged back into develop.

**Comment by climbfuji** [comment]
> I think the problem comes from the previous release because main was not merged back into develop.

Yes, I agree. But now it's all good. Just need to decide if we want to keep those two log files in main or get rid of them (as a follow-up PR).

**Comment by ytremolet** [comment]
> Just need to decide if we want to keep those two log files in main or get rid of them (as a follow-up PR).

I'll leave that up to Benjamin.

**Comment by benjaminmenetrier** [comment]
Those two files are needed when GSI tests (GEOS and GFS cases) are activated. I think we should keep them if possible.

**Comment by climbfuji** [comment]
> Those two files are needed when GSI tests (GEOS and GFS cases) are activated. I think we should keep them if possible.

Fine with me, all you need to do is approve ;-)

**Review by benjaminmenetrier — APPROVED** [review]

**Pull request merged**
